apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization
  template:
    metadata:
      labels:
        app: organization
    spec:
      containers:
        - name: organization
          image: containersoga/organization:104.0.0
          ports:
            - containerPort: 8080
          env:
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: database-user
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: database-password
          - name: MONGO_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongodb
                key: database-name
---
apiVersion: v1
kind: Service
metadata:
  name: organization
spec:
  selector:
    app: organization
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      name: http
  type: LoadBalancer