apiVersion: v1
kind: ServiceAccount
metadata:
  name: organization
  namespace: default
  labels: 
    account: organization
    app: organization
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: department
  namespace: default
  labels: 
    account: department
    app: department
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: employee
  namespace: default
  labels: 
    account: employee
    app: employee
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: service-reader
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: dafault-user-servicereader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: organization-user-servicereader
subjects:
  - kind: ServiceAccount
    name: organization
    namespace: default
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: department-user-servicereader
subjects:
  - kind: ServiceAccount
    name: department
    namespace: default
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: employee-user-servicereader
subjects:
  - kind: ServiceAccount
    name: employee
    namespace: default
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io