apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    # path: /tmp/data
    path: "/run/desktop/mnt/host/c/k8s-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-pvc
spec:
  volumeName: hello-pv
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-volume
spec:
  selector:
    matchLabels:
      app: nginx-volume
  template:
    metadata:
      labels:
        app: nginx-volume
    spec:
      securityContext:
        fsGroup: 101
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: hello-pvc
          readOnly: false
      containers:
      - name: nginx-volume
        image: nginx
        #resources:
        #  limits:
        #    memory: "128Mi"
        #    cpu: "500m"
        #  requests:
        #    memory: "64Mi"
        #    cpu: "250m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage-volume
          mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-volume
spec:
  selector:
    app: nginx-volume
  ports:
  - port: 8086
    targetPort: 80
    name: http
    protocol: TCP
  type: LoadBalancer

